app.test: 1
bot-token: 5860819347:AAEYseogFXAtR8jdrF8_EQCw1R2FPyfLEUs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
server:
  port: 8081
logging:
  level:
    org:
      slf4j: DEBUG
