on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'bot/**'

jobs:
  runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      - run: mvn package -pl bot -am
      - uses: actions/upload-artifact@v3
         with:
           name: bot.jar
           path: bot/target/bot-*.jar 
