on:
  push:
    paths:
      - 'bot/**'
  pull_request:
    paths:
      - 'bot/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bot


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven package
        run: mvn package -pl bot -am

      - uses: actions/upload-artifact@v3
        with:
          name: bot.jar
          path: bot/target/bot-*.jar

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

#      - name: Extract metadata (tags, labels) for Docker
#        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
#        with:
#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/sokolovskayaa/tinkoff-project:latest
